FROM php:8.2-fpm

RUN apt-get update && apt-get install -y \
    git curl libpng-dev libonig-dev libxml2-dev zip unzip libzip-dev nginx

RUN docker-php-ext-install pdo_mysql mbstring exif pcntl bcmath gd zip

COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

WORKDIR /var/www
COPY . .

RUN composer install --optimize-autoloader --no-dev
COPY .env.example .env
RUN php artisan key:generate

RUN chown -R www-data:www-data /var/www \
    && chmod -R 755 storage bootstrap/cache

COPY nginx.conf /etc/nginx/sites-available/default

EXPOSE 9000
CMD ["php-fpm"]